class Exception{
    constructor(erro){
        throw "Exception ao realizar operação: " + erro;
    }
}